### ISSUE TITLE
Schema suggestions

### ISSUE THREAD

**Issue by brtrick** [josephwyang/accord#2]
Well done, very thorough! A few comments:
1. Don't need fields for images/image_urls. We'll use AWS and ActiveStorage to handle those.
2. Might want to keep track of the owner/creator of a server. 
3. Would be good to explicitly note the fields that are foreign keys (you note what they reference in most cases, but identifying them as foreign keys in the table would be good too.)
4. Might want to ensure channel names are unique within the server.
5. Also, just FYI (you may already be aware of this), as part of creating a compound index, rails will automatically create an index for the first column specified, so you don't need to add an explicit index for that column.

**Comment by josephwyang** [comment]
1. Got it! Just took out the image_url columns for users and servers. Is AWS something we want to learn on our own?—still not sure fully what it does or how it connects the images to the right user without storing the information in the database. Also would that mean I don't want an emoji column for the reactions table that stores information of the emoji image?
2. Ah, totally missed that, thank you! Just added an `owner_id` column in the servers table.
3. Just added `foreign key` in the details of all the columns with foreign ids!
4. Would it be okay to keep this feature as is? I think for discord, it allows you to have multiple channels with the same name!
5. Yes! I was aware of that~ but that was a good reminder thank you! Does that mean I shouldn't add `indexed` in the details of such columns? Or was that more just to make sure I knew what was happening under the hood!

Just wanted to add that I'm so grateful for your insane level of attentiveness for my project. I'm sure you might understand how important this project feels to me because you were in my shoes before, so I'm sure you can also understand how grateful I feel for your really helpful and in-depth feedback! Thank you!

**Comment by brtrick** [comment]
https://open.appacademy.io/learn/swe-campus-hybrid/full-stack-project/active-storage-and-aws-s3-hosting-demo

Watch these videos ^^ on implementing AWS when you have a chance.

Yes, you can leave the non-unique channel names if you'd like. (I wasn't
sure if discord allowed that or not.)

 In terms of indexing, I'm fine with however you want to do it in the
design docs. Just remember that you don't have to add a separate index for
the first column of a compound index when doing migrations.

**Comment by josephwyang** [comment]
Hi Brad! I had a quick question about my schema. I wanted my reactions to be unique based on the user and emoji (so users can react multiple times to the same message, but only with different emojis—similar to how discord works). is there a way i can do this without the emoji being in the actual database since I'll be sourcing it from AWS?

**Comment by brtrick** [comment]
1. dms still need foreign keys identified.
2. Adding an owner_id for server works fine as long as you only want to allow one owner. Note that if at some point you wanted to allow multiple owners for a server, you could accomplish that by adding an owner/admin flag to your memberships table instead.
3. With regard to your reactions question, could you store the name of the emoji in the table? (I don't know enough about emojis to know if the names are always unique...)

Closing this issue.
